# Define the output HTML file
$outputFile = "C:\inetpub\wwwroot\PCF_Apps_Report.html"

# Get the current date and time for the "last updated" timestamp
$lastUpdated = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

# Initialize HTML content with improved styling and banner
$htmlContent = @"
<html>
<head>
    <title>PCF Apps Report</title>
    <style>
        body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0; }
        .banner { background-color: #4CAF50; color: white; padding: 10px; text-align: center; font-size: 1.5em; }
        .footer { background-color: #333; color: white; padding: 10px; text-align: center; font-size: 1em; }
        .last-updated { font-size: 0.9em; color: #555; text-align: right; margin: 10px 0; }
        #tableContainer { padding: 20px; }
        table { width: 100%; border-collapse: collapse; font-size: 14px; margin-top: 10px; }
        th, td { padding: 10px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        tr:hover { background-color: #f1f1f1; }
        input[type="text"] { padding: 8px; width: 100%; box-sizing: border-box; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
    </style>
    <script>
        function filterTable() {
            var input, filter, table, tr, td, i, j, txtValue;
            input = document.getElementById('tableFilter');
            filter = input.value.toUpperCase();
            table = document.getElementById('appsTable');
            tr = table.getElementsByTagName('tr');

            for (i = 1; i < tr.length; i++) {
                tr[i].style.display = 'none';
                td = tr[i].getElementsByTagName('td');
                for (j = 0; j < td.length; j++) {
                    if (td[j]) {
                        txtValue = td[j].textContent || td[j].innerText;
                        if (txtValue.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = '';
                            break;
                        }
                    }
                }
            }
        }
    </script>
</head>
<body>
    <div class="banner">PCF Applications Status Report</div>
    <div id="tableContainer">
        <div class="last-updated">Last Updated: $lastUpdated</div>
        <input type="text" id="tableFilter" onkeyup="filterTable()" placeholder="Search for apps, orgs, or spaces...">
        <table id="appsTable">
            <tr>
                <th>Organization</th>
                <th>Space</th>
                <th>App Name</th>
                <th>Status</th>
                <th>Memory Usage (MB)</th>
                <th>CPU Usage (%)</th>
                <th>Disk Usage (MB)</th>
                <th>Uptime (hh:mm:ss)</th>
                <th>Routes</th>
            </tr>
"@

# [The rest of your script goes here, which populates the table rows with data]

# Complete the HTML content with a footer banner
$htmlContent += @"
        </table>
    </div>
    <div class="footer">Generated by PCF Reporting System - $(Get-Date -Format "yyyy")</div>
</body>
</html>
"@

# Write to output file
Set-Content -Path $outputFile -Value $htmlContent

Write-Output "Report generated: $outputFile"
